- hosts: 192.168.56.14
  remote_user: test
  vars:
    appuser: test
    dumbfuzz_repo: https://github.com/m0t/dumbfuzz-c.git
    prospector_repo: https://github.com/m0t/prospector.git
    pybing_repo: https://github.com/m0t/pybing.git
    dumbfuzz_dir: /home/{{appuser}}/dumbfuzz-c
    prospect_dir: /home/{{appuser}}/prospector
    pybing_dir: /home/{{appuser}}/pybing
  tasks:
    - name: install pkgs
      sudo: yes
      apt: pkg={{item}} state=installed
      with_items:
        - sudo
        - git
        - python3
        - gdb
        - python-gevent
        - python-mechanize
        - python3-pip
    - name: install psutil
      sudo: yes
      pip: name=psutil executable=pip3
    - name: create user
      user: name={{ appuser }} home=/home/test/ shell=/bin/bash
      ignore_errors: True
    - name: get pybing
      git: repo={{ pybing_repo }}
         dest={{pybing_dir}}
         accept_hostkey=yes
    - name: get prospector
      git: repo={{ prospector_repo }}
           dest={{prospect_dir}}
           accept_hostkey=yes
    - name: get dumbfuzz
      #sudo_user: "{{ appuser }}"
      #sudo: yes
      git: repo={{ dumbfuzz_repo }}
           dest={{dumbfuzz_dir}}
           accept_hostkey=yes
    - name: pybing symlink
      file: dest={{prospect_dir}}/pybing src={{pybing_dir}} state=link
    #- name: template
    #  template: src=start_hello.sh dest=/opt/test/start_hello.sh
    #- name: restart nginx
    #  service: name=nginx state=restarted enabled=yes